title: "Buttons"
description: |
  Buttons sould be used in situations where a dramatic, obvious action is required. Try not to over use buttons because they should be the primary action for a screen.

patterns:
  basic:
    title: "Basic"
    description: |
      Buttons for the shirts pages.
  ghost:
    title: "Ghost"
    description: |
      Buttons for the jackets pages.
  light:
    title: "Light"
    description: |
      Buttons for the hoodies pages.
  size:
    title: "Size"
    description: |
      A button that is used to select the disired size of the product. All availables sizes are in this pattern.
  nostock:
    title: "No Stock"
    description: |
      For when a certain size is out of stock.
  add:
    title: "Add"
    description: |
      The button to be used on the product for the user to click to add the item to their order.
  checkout:
    title: "Check Out"
    description: |
      A button that leads the user to the checkout. Used on Cart Total Card.
  minus:
    title: "Minus"
    description: |
      To remove 1 from the quanitiy of an item in the cart.
  plus:
    title: "Plus"
    description: |
      To add 1 from the quanitiy of an item in the cart.
  discount:
    title: "Discount"
    description: |
      Button to add a discount in Cart Total Card.
  purchase:
    title: "Purchase"
    description: |
      Button that allows the customer to finalise their purchase.
  submit:
    title: "Submit"
    description: |
      Button that allows the user to submit their email for the newsletter sign up.
  feature:
    title: "Secret Feature Button"
    description: |
      Button that allows the customer to view the full secret featured collection.
