title: "Forms"
description: |
  Fields and buttons that can be pieced together to create forms. They can also be added anywhere applicable.

patterns:
  name:
    title: "Full Name"
    description: |
      Field for the user to input their full name.
  email:
    title: "Email"
    description: |
      Field for the user to input their email.
  phonenumber:
    title: "Phone Number"
    description: |
      Field for the user to input their phone number.
  credit:
    title: "Credit Card"
    description: |
      Field for the user to input their Credit Card.
  address:
    title: "Address"
    description: |
      Field for the user to input their address.
  province:
    title: "Province/State"
    description: |
      Field for the user to input their province/state.
  postal:
    title: "Postal Code"
    description: |
      Field for the user to input their postal code number.
  mailing:
    title: "Newsletter Consent"
    description: |
      A button that allows the user to accept to be subscribed to the MUSHROOM BOY emailing list.
  discount:
    title: "Discount Code"
    description: |
      Field for the user to input a possible discount code. Use only in cart.
  warning:
    title: "Warning"
    description: |
      A warning that pops up when the user is missing some information or a field.
  quantity:
    title: "Quantity"
    description: |
      A field the shows up on the product card in the cart as well as in the product display page that allows the user to add or subtract the quantity of their order.
